### ISSUE TITLE
How to require the middleware instead of import?

### ISSUE THREAD

**Issue by sfu69** [zazoomauro/node-dependency-injection-express-middleware#12]
I'm trying to use require instead of import and I struggle with it. I'm also pretty new to node.js

```js
#app.js

const Express = require('express');

const app = Express();

const NDIMiddleware =  require('node-dependency-injection-express-middleware');

const services = {serviceFilePath: './resources/services.yml'}
```

And I don't know where to go from here without throwing any errors like in those examples

```js
#app.js
app.use(new NDIMiddleware.default(services).middleware());
```

```yml
#services.yml
services:
  mailHandler:
    class:     './src/MailHandler'
```

```js
#/src/MailHandler.js
class MailHandler {
    constructor() {}
}


module.exports = MailHandler;
```

```
> dpasw@0.0.0 start /home/paul/GIT/dpasw
> node ./bin/www

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'src/MailHandler'
Require stack:
- /home/user/GIT/project/node_modules/node-dependency-injection/dist/lib/Loader/FileLoader.js
- /home/user/GIT/project/node_modules/node-dependency-injection/dist/lib/Loader/JsFileLoader.js
- /home/user/GIT/project/node_modules/node-dependency-injection/dist/lib/index.js
- /home/user/GIT/project/node_modules/node-dependency-injection-express-middleware/dist/index.js
- /home/user/GIT/project/app.js
- /home/user/GIT/project/bin/www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)```

**Comment by sfu69** [comment]
Found the solution. Problem with pathing as already described above by the error output.

That's what I used before
```yml
#services.yml
services:
  mailHandler:
    class:     './src/MailHandler'
```
That's what I had to use instead:
```#services.yml
services:
  mailHandler:
    class: ../../../../../src/MailHandler
```

It seems that due to require there are problems to find the correct path.
```sh
node_modules/node-dependency-injection-express-middleware/dist/index.js
```

I need to go all those files back until I am at root of the project. I've no idea how to fix it besides adding all those ../ into the defaultDir setting

****

Should be the same solution as for this problem here:

Duplicate of # https://github.com/zazoomauro/node-dependency-injection/issues/152
